# Generated by Django 5.1.4 on 2024-12-15 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('estado', models.CharField(choices=[('COMIENDO', 'Comiendo'), ('DORMIDO', 'Dormido'), ('ENFERMO', 'Enfermo'), ('ESTRESADO', 'Estresado'), ('HAMBRIENTO', 'Hambriento'), ('HERIDO', 'Herido'), ('NORMAL', 'Normal')], default='NORMAL', max_length=100)),
                ('dieta', models.CharField(choices=[('CARNIVORE', 'Carnívoro'), ('HERBIVORE', 'Herbívoro'), ('OMNIVORE', 'Omnívoro')], default='CARNIVORE', max_length=100)),
                ('cuerpo', models.CharField(choices=[('INVERTEBRADO', 'Invertebrado'), ('VERTEBRADO', 'Vertebrado')], default='VERTEBRADO', max_length=100)),
                ('zona', models.CharField(choices=[('ESTE', 'Este'), ('NORTE', 'Norte'), ('OESTE', 'Oeste'), ('SUR', 'Sur')], default='ESTE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('contador', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateField()),
                ('valor', models.FloatField()),
                ('numero', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('nombre', models.CharField(default='Nombre desconocido', max_length=200)),
                ('edad', models.IntegerField(default=0)),
                ('salario', models.FloatField()),
                ('fecha_ingreso', models.DateField()),
                ('zona', models.CharField(choices=[('ESTE', 'Este'), ('NORTE', 'Norte'), ('OESTE', 'Oeste'), ('SUR', 'Sur')], default='ESTE', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('nombre', models.CharField(default='Nombre desconocido', max_length=200)),
                ('edad', models.IntegerField(default=0)),
                ('boletos_comprados', models.ManyToManyField(related_name='clientes', to='Zoo.boleto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalAdministrativo',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Zoo.empleado')),
                ('departamento', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('Zoo.empleado',),
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_medico', to='Zoo.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Zoological',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('horario_apertura', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('direction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoological', to='Zoo.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('numero_jaula', models.CharField(max_length=10, unique=True)),
                ('esta_limpio', models.BooleanField(default=True)),
                ('zoological', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jaulas', to='Zoo.zoological')),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Zoo.empleado')),
                ('animales_a_cargo', models.ManyToManyField(related_name='cuidadores', to='Zoo.animal')),
            ],
            options={
                'abstract': False,
            },
            bases=('Zoo.empleado',),
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Zoo.empleado')),
                ('recorrido', models.CharField(choices=[('ESTE', 'Este'), ('NORTE', 'Norte'), ('OESTE', 'Oeste'), ('SUR', 'Sur')], default='ESTE', max_length=10)),
                ('clientes', models.ManyToManyField(related_name='guias', to='Zoo.cliente')),
            ],
            options={
                'abstract': False,
            },
            bases=('Zoo.empleado',),
        ),
        migrations.CreateModel(
            name='PersonalLimpieza',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Zoo.empleado')),
                ('jaulas', models.ManyToManyField(related_name='personal_limpieza', to='Zoo.jaula')),
            ],
            options={
                'abstract': False,
            },
            bases=('Zoo.empleado',),
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Zoo.empleado')),
                ('especialidad', models.CharField(max_length=100)),
                ('animales_asignados', models.ManyToManyField(related_name='veterinarios', to='Zoo.animal')),
            ],
            options={
                'abstract': False,
            },
            bases=('Zoo.empleado',),
        ),
    ]
